# Generated by Django 5.2.5 on 2025-09-24 20:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_pension', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('documentos', models.FileField(upload_to='documentos/')),
                ('estado_expediente', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=50)),
            ],
            options={
                'db_table': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9', regex='^\\d{1,2}\\d{3}\\d{3}-[\\dkK]$')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'gestores',
            },
        ),
        migrations.CreateModel(
            name='ItemChequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('is_critical', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'item_chequeo',
            },
        ),
        migrations.CreateModel(
            name='ListaChequeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'lista_chequeo',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_auditoria', models.DateField(auto_now_add=True)),
                ('calificacion', models.IntegerField(default=0, help_text='Calificacion de 0 a 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirementApp.expediente')),
                ('lista_chequeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirementApp.listachequeo')),
            ],
            options={
                'db_table': 'auditoria_expediente',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirementApp.gestor'),
        ),
        migrations.CreateModel(
            name='ItemAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_auditoria', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No Cumple')], max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('auditoria_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirementApp.auditoriaexpediente')),
                ('item_chequeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirementApp.itemchequeo')),
            ],
            options={
                'db_table': 'item_auditoria',
            },
        ),
        migrations.AddField(
            model_name='itemchequeo',
            name='lista_chequeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retirementApp.listachequeo'),
        ),
    ]
